### ISSUE TITLE
class-setup fails with runtime error

### ISSUE THREAD

**Issue by autarch** [autarch/intro-to-go-class-code#3]
David Hand and a few others saw this when trying to run `class-setup` for the June, 2018 class:

```
I got this when I attempted to run your setup binary before I'd created the $GOPATH dir:

$ ./class-setup-linux-amd64 

  GOPATH is set to /home/ptolemarch/.go. Use that path for class exercises? (y/n) panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/Bowery/prompt.(*Buffer).Refresh(0xc42006dc68, 0x1000, 0x1000)
    /home/autarch/go/src/github.com/Bowery/prompt/buffer_unix.go:54 +0x4f1
github.com/Bowery/prompt.(*Terminal).setup(0xc4200ae100, 0xc42006dc68, 0x4fb0e0, 0xc4200a8050, 0x7f0ba42f3d90, 0x0, 0x0)
    /home/autarch/go/src/github.com/Bowery/prompt/term.go:212 +0xa4
github.com/Bowery/prompt.(*Terminal).prompt(0xc4200ae100, 0xc42006dc68, 0x4fb0e0, 0xc4200a8050, 0x1, 0xc4200b8120, 0x52, 0xc4200b810a)
    /home/autarch/go/src/github.com/Bowery/prompt/term.go:317 +0x67
github.com/Bowery/prompt.(*Terminal).GetPrompt(0xc4200ae100, 0xc4200b80c0, 0x51, 0xc42006dd20, 0x441117, 0x0, 0xc42006dd38)
    /home/autarch/go/src/github.com/Bowery/prompt/term.go:165 +0x11e
github.com/Bowery/prompt.(*Terminal).Custom(0xc4200ae100, 0xc4200b80c0, 0x51, 0x4ee498, 0x7, 0xc4200b80c0, 0x51, 0xc42006dd88)
    /home/autarch/go/src/github.com/Bowery/prompt/term.go:130 +0x82
github.com/Bowery/prompt.(*Terminal).Ask(0xc4200ae100, 0xc4200a6320, 0x4a, 0x2, 0x2, 0xc4200a6320)
    /home/autarch/go/src/github.com/Bowery/prompt/term.go:101 +0x85
github.com/Bowery/prompt.Ask(0xc4200a6320, 0x4a, 0x0, 0x0, 0x0)
    /home/autarch/go/src/github.com/Bowery/prompt/prompt.go:62 +0x92
main.askOrDie(0xc4200a62d0, 0x48, 0x11)
    /home/autarch/projects/intro-to-go-class/gopath/src/github.com/autarch/intro-to-go-class-code/class-setup/class-setup.go:68 +0x70
main.getGopath(0x0, 0x0, 0xc42006df01)
    /home/autarch/projects/intro-to-go-class/gopath/src/github.com/autarch/intro-to-go-class-code/class-setup/class-setup.go:58 +0xd4
main.main()
    /home/autarch/projects/intro-to-go-class/gopath/src/github.com/autarch/intro-to-go-class-code/class-setup/class-setup.go:18 +0x45
```

**Comment by autarch** [comment]
I cannot reproduce. I wonder if this was fixed in the prompt package at some point after my last `go get` of it.
